name: Thank users for new issue

on:
  issues: 
    types: [opened]

jobs:
  create-message:
    runs-on: ubuntu-latest
    steps:
      - name: Leave thank-you message
        uses: actions/github-script@0.8.0
        with:
          github-token: "{% raw %}${{secrets.GITHUB_TOKEN}}{% endraw %}"
          script: |
              github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🎉 You've created this issue comment using GitHub Script!!!"
              })
